apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 10 }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      terminationGracePeriodSeconds: 60
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.application.environment | quote }}
        - name: ASPNETCORE_URLS
          value: {{ .Values.application.urls | quote }}
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold": 5
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold": 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
