# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
application:
  app: CI_ENVIRONMENT_SLUG
  track: stable
  tier: web
#  urls: http://0.0.0.0:5000
#  environment: development
livenessprobe:
  path: /ping
readinessprobe:
  path: /health
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 5000
  internalPort: 5000
ingress:
  tls_enabled: true
postgresql:
  enabled: false
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi
podAnnotations:
  prometheus.io/scrape: "\"true\""
